[workspace]

[package]
name = "sandbox"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dotenvy = "0.15"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
axum = { version = "0.8", features = ["multipart"] }
glob = "0.3"
regex = "1"
tower-http = { version = "0.7", features = ["catch-panic", "cors"] }
tokio-util = { version = "0.7", features = ["io"] }
utoipa = { version = "5", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "9", features = ["axum"] }
uuid = { version = "1", features = ["v4"] }
