[package]
name = "mcp-server-demo"
version = "0.1.0"
edition = "2024"

[workspace]

[[bin]]
name = "mcp-client-demo"
path = "src/mcp-client-demo.rs"

[[bin]]
name = "mcp-server-stdio"
path = "src/mcp-server-stdio.rs"

[[bin]]
name = "mcp-client-stdio"
path = "src/mcp-client-stdio.rs"

[[bin]]
name = "mcp-bash"
path = "src/mcp-bash.rs"

[dependencies]
rmcp = { version = "1.7.0", features = [
    "client",
    "server",
    "macros",
    "transport-child-process",
    "transport-io",
    "transport-streamable-http-client-reqwest",
    "transport-streamable-http-server",
] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1"
fasteval = "0.2.4"
axum = "0.8.9"
