### DeepSeek API 非流式响应接口测试
POST https://api.deepseek.com/chat/completions
Content-Type: application/json
Authorization: Bearer {{DEEPSEEK_API_KEY}}

{
  "model": "deepseek-v4-flash",
  "messages": [
    {
      "role": "user",
      "content": "你好，你是？"
    }
  ],
  "thinking": {
    "type": "enabled"
  },
  "stream": false
}
