#!/usr/bin/env python
# -*- coding: utf-8 -*-
import json
import os

import requests
from mcp.server.fastmcp import FastMCP

mcp = FastMCP(name="三方 API")

APP_ID = os.getenv("LLMOPS_APP_ID", "")
LLMOPS_API = os.getenv("LLMOPS_API", "https://llmops.shortvar.com/api/openapi/chat")
LLMOPS_API_KEY = os.getenv("LLMOPS_API_KEY", "")


@mcp.tool()
async def call_llmops_agent(query: str) -> str:
    """调用外部 Agent 实现对 Query 的回答。/ Call an external agent to answer the query.

    Args:
        query: 用户需要提交的问题。/ User query.

    Returns:
        外部 Agent 生成的最终答案。/ Final answer generated by the external agent.
    """
    if not APP_ID:
        return "缺少环境变量 LLMOPS_APP_ID"
    if not LLMOPS_API_KEY:
        return "缺少环境变量 LLMOPS_API_KEY"

    answer = ""
    with requests.request(
        "POST",
        LLMOPS_API,
        headers={
            "Content-Type": "application/json",
            "Accept": "application/json",
            "Authorization": f"Bearer {LLMOPS_API_KEY}",
        },
        json={"query": query, "app_id": APP_ID, "stream": True},
    ) as resp:
        resp.raise_for_status()
        for line in resp.iter_lines(decode_unicode=True):
            if line and line.startswith("data:"):
                data = line.removeprefix("data:").strip()
                if data and data != "[DONE]":
                    resp_obj = json.loads(data)
                    if resp_obj.get("event") == "agent_message":
                        answer += resp_obj.get("answer", "")

    return answer.strip()


if __name__ == "__main__":
    mcp.run(transport="streamable-http")
