//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "mcp_servers")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub uuid: Uuid,
    pub user_id: Option<Uuid>,
    pub status: Option<String>,
    pub is_deleted: Option<bool>,
    #[sea_orm(column_type = "Text", nullable)]
    pub remark: Option<String>,
    pub transport: String,
    pub enabled: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub env: Option<Json>,
    pub command: Option<String>,
    pub args: Option<Vec<String>>,
    pub url: Option<String>,
    pub headers: Option<Json>,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
