//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "sessions")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub uuid: Option<Uuid>,
    pub sandbox_id: Option<String>,
    pub task_id: Option<String>,
    pub title: Option<String>,
    pub unread_message_count: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub latest_message: Option<String>,
    pub latest_message_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub events: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub files: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub memories: Option<Json>,
    pub status: Option<String>,
    pub user_id: Option<Uuid>,
    pub is_deleted: Option<bool>,
    #[sea_orm(column_type = "Text", nullable)]
    pub remark: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
