/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as SchedulesRouteImport } from './routes/schedules'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as SessionsIdRouteImport } from './routes/sessions/$id'
import { Route as SessionsIdNovncRouteImport } from './routes/sessions/$id_.novnc'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdNovncRoute = SessionsIdNovncRouteImport.update({
  id: '/sessions/$id_/novnc',
  path: '/sessions/$id/novnc',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/schedules': typeof SchedulesRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/sessions/$id/novnc': typeof SessionsIdNovncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/schedules': typeof SchedulesRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/sessions/$id/novnc': typeof SessionsIdNovncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/schedules': typeof SchedulesRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/sessions/$id_/novnc': typeof SessionsIdNovncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/library'
    | '/schedules'
    | '/demo/tanstack-query'
    | '/sessions/$id'
    | '/sessions/$id/novnc'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/library'
    | '/schedules'
    | '/demo/tanstack-query'
    | '/sessions/$id'
    | '/sessions/$id/novnc'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/library'
    | '/schedules'
    | '/demo/tanstack-query'
    | '/sessions/$id'
    | '/sessions/$id_/novnc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LibraryRoute: typeof LibraryRoute
  SchedulesRoute: typeof SchedulesRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  SessionsIdRoute: typeof SessionsIdRoute
  SessionsIdNovncRoute: typeof SessionsIdNovncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id_/novnc': {
      id: '/sessions/$id_/novnc'
      path: '/sessions/$id/novnc'
      fullPath: '/sessions/$id/novnc'
      preLoaderRoute: typeof SessionsIdNovncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LibraryRoute: LibraryRoute,
  SchedulesRoute: SchedulesRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  SessionsIdRoute: SessionsIdRoute,
  SessionsIdNovncRoute: SessionsIdNovncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
